# hosts
h1[0]="h1_a"
h2[0]="h2_a"
h3[0]="h_h3"
h4[0]="h_h4"
h1[image]="kathara/base"
h2[image]="kathara/base"
h3[image]="kathara/base"
h4[image]="kathara/base"

# switch A (transit): port1=h1, port2=h2, port3=B, port4=C
a[0]="h1_a"
a[1]="h2_a"
a[2]="a_b"
a[3]="a_c"
a[image]="kathara/p4"

# switch B (classifier): port1=A, port2=D, port3=C, port4=F
b[0]="a_b"
b[1]="b_d"
b[2]="b_c"
b[3]="b_f"
b[image]="kathara/p4"

# switch C (transit): port1=A, port2=B, port3=E, port4=G
c[0]="a_c"
c[1]="b_c"
c[2]="c_e"
c[3]="c_g"
c[image]="kathara/p4"

# switch D (SFF1): port1=B, port2=F, port3=SF1, port4=SF2
d[0]="b_d"
d[1]="d_f"
d[2]="d_sf1"
d[3]="d_sf2"
d[image]="kathara/p4"

# switch E (SFF2): port1=C, port2=G, port3=SF3
e[0]="c_e"
e[1]="e_g"
e[2]="e_sf3"
e[image]="kathara/p4"

# switch F (transit): port1=B, port2=D, port3=G, port4=H
f[0]="b_f"
f[1]="d_f"
f[2]="f_g"
f[3]="f_h"
f[image]="kathara/p4"

# switch G (transit): port1=C, port2=E, port3=F, port4=H
g[0]="c_g"
g[1]="e_g"
g[2]="f_g"
g[3]="g_h"
g[image]="kathara/p4"

# switch H (transit): port1=F, port2=G, port3=h3, port4=h4
h[0]="f_h"
h[1]="g_h"
h[2]="h_h3"
h[3]="h_h4"
h[image]="kathara/p4"

# service functions (P4 reflector)
sf1[0]="d_sf1"
sf2[0]="d_sf2"
sf3[0]="e_sf3"
sf1[image]="kathara/p4"
sf2[image]="kathara/p4"
sf3[image]="kathara/p4"
